#!/bin/bash
# Download all 64 高岛易断 markdown files from GitHub
BASE_URL="https://raw.githubusercontent.com/zhclassmates/Nothing/main/gao_md"
OUT_DIR="$(dirname "$0")/../data/gao_md"
mkdir -p "$OUT_DIR"

FILES=(
"modified_gao_01乾为天.md"
"modified_gao_02坤为地.md"
"modified_gao_03水雷屯.md"
"modified_gao_04山水蒙.md"
"modified_gao_05水天需.md"
"modified_gao_06天水讼.md"
"modified_gao_07地水师.md"
"modified_gao_08水地比.md"
"modified_gao_09风天小畜.md"
"modified_gao_10天泽履.md"
"modified_gao_11地天泰.md"
"modified_gao_12天地否.md"
"modified_gao_13天火同人.md"
"modified_gao_14火天大有.md"
"modified_gao_15地山谦.md"
"modified_gao_16雷地豫.md"
"modified_gao_17泽雷随.md"
"modified_gao_18山风蛊.md"
"modified_gao_19地泽临.md"
"modified_gao_20风地观.md"
"modified_gao_21火雷噬嗑.md"
"modified_gao_22山火贲.md"
"modified_gao_23山地剥.md"
"modified_gao_24地雷复.md"
"modified_gao_25天雷无妄.md"
"modified_gao_26山天大畜.md"
"modified_gao_27山雷颐.md"
"modified_gao_28泽风大过.md"
"modified_gao_29坎为水.md"
"modified_gao_30离为火.md"
"modified_gao_31泽山咸.md"
"modified_gao_32雷风恒.md"
"modified_gao_33天山遁.md"
"modified_gao_34雷天大壮.md"
"modified_gao_35火地晋.md"
"modified_gao_36地火明夷.md"
"modified_gao_37风火家人.md"
"modified_gao_38火泽睽.md"
"modified_gao_39水山蹇.md"
"modified_gao_40雷水解.md"
"modified_gao_41山泽损.md"
"modified_gao_42风雷益.md"
"modified_gao_43泽天夬.md"
"modified_gao_44天风姤.md"
"modified_gao_45泽地萃.md"
"modified_gao_46地风升.md"
"modified_gao_47泽水困.md"
"modified_gao_48水风井.md"
"modified_gao_49泽火革.md"
"modified_gao_50火风鼎.md"
"modified_gao_51震为雷.md"
"modified_gao_52艮为山.md"
"modified_gao_53风山渐.md"
"modified_gao_54雷泽归妹.md"
"modified_gao_55雷火丰.md"
"modified_gao_56火山旅.md"
"modified_gao_57巽为风.md"
"modified_gao_58兑为泽.md"
"modified_gao_59风水涣.md"
"modified_gao_60水泽节.md"
"modified_gao_61风泽中孚.md"
"modified_gao_62雷山小过.md"
"modified_gao_63水火既济.md"
"modified_gao_64火水未济.md"
)

for f in "${FILES[@]}"; do
  num=$(echo "$f" | grep -oP '\d{2}')
  out="$OUT_DIR/${num}.md"
  if [ -f "$out" ]; then
    echo "Skip $num (exists)"
    continue
  fi
  encoded=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$f'))")
  echo "Downloading $num..."
  curl -sL "${BASE_URL}/${encoded}" -o "$out"
  sleep 0.3
done
echo "Done. $(ls "$OUT_DIR"/*.md 2>/dev/null | wc -l) files downloaded."
